# Test core parts of the package, that are not:
# * Shell dependent;
# * Build-system dependent;
# * Platform dependent.
#
name: core
on:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/core.yaml'
      - '!src/rez/utils/_version.py'
      - '!**.md'
  push:
    paths:
      - 'src/**'
      - '.github/workflows/core.yaml'
      - '!src/rez/utils/_version.py'
      - '!**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: main
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - '2.7'
          - '3.7'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python ${{ matrix.python-version }}
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
          os: ubuntu-latest

      - name: Install Rez
        shell: bash
        run: |
          set -ex
          mkdir ./installdir

          if [[ "${{ matrix.python-version }}" == "2.7" ]]; then
              eval "$(conda shell.bash hook)"
              conda activate python
          fi

          python ./install.py ./installdir

      - name: Install Rez test dependencies
        run: |
          ./installdir/bin/rez/rez-python -m pip install pytest-cov

      # TODO: Add a --core rez-selftest option. Some test suites (eg test_context)
      # have some 'core' parts (eg not reliant on a shell). It would be good to just
      # run those parts when --core is present, rather than skipping the entire
      # test class. This will be easier once ported to pytest.
      - name: Run Rez Tests
        run: |
          ./installdir/bin/rez/rez-selftest -v \
            --config \
            --copy_package \
            --formatter \
            --imports \
            --packages \
            --package_filter \
            --packages_order \
            --resources_ \
            --rex \
            --schema \
            --solver \
            --version
