name: sphinx
on:
  release:
    types: [released]

jobs:
  build:
    name: Build Sphinx Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 2.7

      - name: Sphinx Build
        run: python docs/build.py --no-docker

      - uses: actions/upload-artifact@v2
        with:
          name: html-docs
          path: docs/_build

  publish:
    name: Publish to GitHub pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: html-docs
          path: .

      - name: Setup git repository
        run: |
          git init .
          git config --global user.name "github.com/${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@${{ github.sha }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git checkout -B gh-pages

      - name: Git commit, force push gh-pages
        run: |
          git add .
          git commit \
            -m "Generated from GitHub "${{ github.workflow }}" Workflow" \
            && git push --force origin gh-pages \
            || echo "Nothing new to commit"
