name: ubuntu
on:
  pull_request:
    paths-ignore:
      - '.github/docker/**'
      - '.github/workflows/windows-docker-image.yaml'
      - 'src/rez/utils/_version.py'
      - 'wiki/**'
      - 'metrics/**'
      - '**.md'
  push:
    paths-ignore:
      - '.github/docker/**'
      - '.github/workflows/windows-docker-image.yaml'
      - 'src/rez/utils/_version.py'
      - 'wiki/**'
      - 'metrics/**'
      - '**.md'

jobs:
  main:
    name: main
    runs-on: ubuntu-${{ matrix.os-version }}

    strategy:
      matrix:
        os-version:
          - '16.04'
          - '18.04'
        python-version:
          - '2.7'
          - '3.6'
          - '3.7'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify cmake
        run: |
          cmake --version

      - name: Verify pwsh
        run: |
          pwsh --version

      - name: Install csh
        run: |
          sudo apt-get install -y csh

      - name: Install tcsh
        run: |
          sudo apt-get install -y tcsh

      - name: Install zsh
        run: |
          sudo apt-get install -y zsh

      - name: Install Rez
        run: |
          mkdir ./build
          python ./install.py ./build

      - name: Run Rez Tests
        run: |
          ./build/bin/rez/rez-selftest
