name: wiki
on:
  release:
    types: [released]
  push:
    paths:
      - '.github/workflows/wiki-build.yaml'
      - 'wiki/**'
      - src/rez/rezconfig.py
env:
  CLONE_URL: "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git"

jobs:
  build:
    name: Build Wiki Artifact
    runs-on: ubuntu-latest
    env:
      TEMP_WIKI_DIR: "wiki/.rez-gen-wiki-tmp"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # required to generate credits list

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Build Wiki
        working-directory: wiki
        run: |
          rezver=$(cat ./src/rez/utils/_version.py | grep -w _rez_version | tr '"' ' ' | awk '{print $NF}')

          python update-wiki.py \
            --keep-temp \
            --no-push \
            --github-release=${rezver} \
            --wiki-dir="${{ github.workspace }}"/"${{ env.TEMP_WIKI_DIR }}" \
            --wiki-url="${{ env.CLONE_URL }}"

      - uses: actions/upload-artifact@v2
        with:
          name: wiki-markdown
          path: ${{ env.TEMP_WIKI_DIR }}

  publish:
    name: Publish to GitHub Wiki
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
      - uses: actions/download-artifact@v2
        with:
          workflow: wiki-build.yaml
          workflow_conclusion: success
          name: wiki-markdown
          path: .

      - name: Setup git config
        run: |
          git config --global user.name "github.com/${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@${{ github.sha }}"

      - name: Git commit and push
        run: |
          git commit \
              -m "Generated from GitHub "${{ github.workflow }}" Workflow" \
              -m "See https://github.com/${{ github.repository }}/runs/${GITHUB_ACTION}" \
              || exit 0
          git remote set-url origin "${{ env.CLONE_URL }}"
          git push origin master
